export const FETCHING_EVENT = 'FETCHING_EVENT';
export const FETCHING_EVENT_FAILED = 'FETCHING_EVENT_FAILED';
export const FETCHING_EVENT_SUCCESS = 'FETCHING_EVENT_SUCCESS';

export const CREATING_EVENT = 'CREATING_EVENT';
export const CREATING_EVENT_FAILED = 'CREATING_EVENT_FAILED';
export const CREATING_EVENT_SUCCESS = 'CREATING_EVENT_SUCCESS';