version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo/admin
    steps:
      - checkout
      - run: ls -l ~/repo
      - restore_cache: # special step to restore the dependency cache
          keys:
            - v1-dependencies-{{ checksum "./admin/package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: v1-dependencies-{{ checksum "./admin/package.json" }}
          paths:
            - ./admin/node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: ls -la
          command: |
            ./cc-test-reporter before-build
            yarn run test -- --coverage
            ./cc-test-reporter after-build --exit-code $?